language: cpp

before_install:
  - git clone https://github.com/google/googletest.git

install:
  - sudo apt-get install lcov
  - gem install coveralls-lcov

script:
  - make GTEST_DIR=googletest/googletest

after_success:
  - ./test_run.out
  - lcov --directory . --capture --output-file coverage.info
  - lcov --remove coverage.info 'tests/*' 'usr/*' '*gtest*' '*googletest*' --output-file coverage.info
  - lcov --list coverage.info
  - coveralls-lcov coverage.info

notifications:
  email:
    on_success: change
    on_failure: change
